# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: ./build_resume.sh pdflatex -on-error Resume.tex
  displayName: "Build Resume"

- script: |
    pip3 install pipenv
    pipenv install
    pipenv run upload_dropbox.py --source=Resume/Resume.pdf --target=/Resume.pdf
  displayName: "Upload Resume to Dropbox"
  env:
    DROPBOX_TOKEN : $(DROPBOX_TOKEN)