name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build Resume
      run:  make build-pdf
    - name: Upload Resume to Dropbox
      run: make upload-pdf DROPBOX_TOKEN=$(DROPBOX_TOKEN)
